//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stu_position
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public position()
        {
            this.wifisignals = new HashSet<wifisignal>();
        }
    
        public int Id { get; set; }
        public string pixelxy { get; set; }
        public string pname { get; set; }
    
        public virtual ICollection<wifisignal> wifisignals { get; set; }
    }
}
