//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stu_position
{
    using System;
    using System.Collections.Generic;
    
    public partial class wifisignal
    {
        public int Id { get; set; }
        public int wifirouterID { get; set; }
        public int positionID { get; set; }
        public int signal { get; set; }
    
        public virtual position position { get; set; }
        public virtual wifirouter wifirouter { get; set; }
    }
}
